### PR TITLE
fix: update hooks on scroller of Vimium C

### PR DESCRIPTION
**Pull request by gdh1995**
### describe the bug/feature 解决的问题或新增的功能

This fixes what's said in https://github.com/EdgeTranslate/EdgeTranslate/pull/225#issuecomment-888185998 .

### summary of code change 描述发生的改变

The hook on scroller of Vimium C now passes all arguments and returns any result.

### CODE REVIEW

**Comment by Mark-Fenng** [comment]
Did you choose the wrong target branch?😅

**Comment by gdh1995** [comment]
&nbsp;Um, Yes, I did.&nbsp; I'll close this and pull a new then.



---Original---
From: "Lucky ***@***.***&gt;
Date: Wed, Jul 28, 2021 21:36 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [EdgeTranslate/EdgeTranslate] fix: update hooks on scroller of Vimium C (#238)




 
Did you choose the wrong target branch?😅

**Comment by gdh1995** [comment]
Finished - I just find GitHub allow me to modify the "target base".

**Comment by Mark-Fenng** [comment]
Thank you for your contribution and responsibility!

**Pull request merged**
