### PR TITLE
Fixed gif and other links

### PR DESCRIPTION
**Pull request by ViktorOn**
Add a link to this guide from the main page

### CODE REVIEW

**Comment by ViktorOn** [comment]
And add a folder in the EdgeTranslate/docs/wiki/ru directory, and I'll slowly start filling it. I won't make a separate request for this, okay?

**Comment by Mark-Fenng** [comment]
Great work so far, separate requests are also welcomed.

**Comment by ViktorOn** [comment]
> Add a link to this guide from the main page

> And add a folder in the EdgeTranslate/docs/wiki/ru directory, and I'll slowly start filling it. I won't make a separate request for this, okay?

Both of my requests were never fulfilled, which is a bit hurtful. :(

**Comment by Mark-Fenng** [comment]
what do you mean fulfilled

**Comment by ViktorOn** [comment]
> what do you mean fulfilled

Similar words in meaning: executed, completed

**Pull request merged**
